[build]
builder = "NIXPACKS"
watchPatterns = ["**/*.js", "**/*.json", "**/*.toml", "**/*.ts", "**/*.tsx", "**/*.jsx"]
useMetalBuild = false

[build.nixpacks]
configPath = "nixpacks.toml"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
