[build]
builder = "NIXPACKS"
watchPatterns = ["**/*.js", "**/*.json", "**/*.toml"]

[deploy]
startCommand = "cd Documents/ratemyra/server && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
